"""enabled pictures

Revision ID: 0cac6d5ab2d1
Revises: a1d35479eea0
Create Date: 2024-07-03 16:13:07.458486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cac6d5ab2d1'
down_revision = 'a1d35479eea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('is_pest',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('detection', schema=None) as batch_op:
        batch_op.alter_column('critter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('detection_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection', schema=None) as batch_op:
        batch_op.alter_column('detection_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('critter_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.alter_column('is_pest',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
