"""Add image_filename column to Detection

Revision ID: 45dc14e98178
Revises: 0cac6d5ab2d1
Create Date: 2024-07-03 16:23:45.994046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45dc14e98178'
down_revision = '0cac6d5ab2d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
