"""Create detection and critter tables

Revision ID: a1d35479eea0
Revises: f4e6e700984b
Create Date: 2024-07-02 14:56:35.706904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d35479eea0'
down_revision = 'f4e6e700984b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('critter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_pest', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_time', sa.DateTime(), nullable=False),
    sa.Column('critter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['critter_id'], ['critter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pest_identification', sa.VARCHAR(length=64), nullable=False),
    sa.Column('is_pest', sa.BOOLEAN(), nullable=False),
    sa.Column('detection_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('detection')
    op.drop_table('critter')
    # ### end Alembic commands ###
