"""Initial migration.

Revision ID: f4e6e700984b
Revises: 
Create Date: 2024-06-30 19:33:14.691401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e6e700984b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pest_identification', sa.String(length=64), nullable=False),
    sa.Column('is_pest', sa.Boolean(), nullable=False),
    sa.Column('detection_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
