"""initial migration

Revision ID: fa35c9f86954
Revises: 
Create Date: 2024-07-24 16:26:15.869413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa35c9f86954'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('critter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('is_pest', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('critter_id', sa.Integer(), nullable=True),
    sa.Column('detection_time', sa.DateTime(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['critter_id'], ['critter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection')
    op.drop_table('critter')
    # ### end Alembic commands ###
